[package]
name = "tklib"
version = "0.1.0"
authors = ["MickTK"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
json = "0.12.4"
image = "0.25.1"
ureq = "2.9.7"
url = "2.5.1"
csv = "1.3.0"
